title: áˆá‰ áˆ» HOOD
email: info@habeshahood.com
description: >- 
  ğŸµ Showcasing the latest in Habesha music, talent creativity & culture ğŸ‡ªğŸ‡¹ğŸ¤ğŸ”¥
timezone: UTC
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://www.habeshahood.com" # the base hostname & protocol for your site
logo: 'assets/images/logo.png'  # should be in your _config.yml or equivalent
favicon: 'assets/images/favicon.ico'
author: áˆá‰ áˆ»
paginate: 30
disqus: 'website'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: áˆá‰ áˆ» HOOD Team
    display_name: Tewdros
    avatar: 'assets/images/team.png'
    email: team@habeshahood.com
    web: https://www.habeshahood.com
   
# Social
social:
  telegram: https://www.telegram.me/officialhabeshahood
  instagram: https://www.instagram.com/officialhabeshahood/
  facebook: https://www.facebook.com/officialhabeshahood
  tiktok: https://www.tiktok.com/@officialhabeshahood
  medium: https://www.medium.com/@habeshahood
  youtube: https://www.youtube.com/@habeshahood
  spotify: https://open.spotify.com/artist/2E41Kn2v9djgwBsMtTYMe2
# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
